### ISSUE TITLE
could not repeat the same command after the 1st failure

### ISSUE THREAD

**Issue by bogdando** [mwhahaha/task-core#11]
Following the OpenStack 2021 PTG hackfest steps https://etherpad.opendev.org/p/tripleo-directord-hackfest
I had to reboostrap directord and repeat the deployment command once more, but now I have:

(directord) [nonroot@node0 services]$ task-core -s . -i ~/task-core-inventory-hackfest.yaml -r ../basic/2node_roles.yaml -d                                                             
[2021-10-21 13:42:54,032] [DEBUG] Logging setup
[2021-10-21 13:42:54,032] [INFO] Loading services from .
[2021-10-21 13:42:54,035] [ERROR] Error loading ./basic_config.yaml
Traceback (most recent call last):
  File "/opt/directord/bin/task-core", line 10, in <module>
    sys.exit(main())
  File "/home/nonroot/task-core/task_core/cmd.py", line 138, in main
    mgr = TaskManager(args.services_dir, args.inventory_file, args.roles_file)
  File "/home/nonroot/task-core/task_core/manager.py", line 49, in __init__
    self.load()
  File "/home/nonroot/task-core/task_core/manager.py", line 53, in load
    self.load_services()
  File "/home/nonroot/task-core/task_core/manager.py", line 65, in load_services
    svc = Service(file)
  File "/home/nonroot/task-core/task_core/service.py", line 21, in __init__
    ServiceSchemaValidator.instance().validate(self._data)
  File "/home/nonroot/task-core/task_core/schema.py", line 48, in validate
    return jsonschema.validate(obj, self.schema)
  File "/home/nonroot/task-core/task_core/schema.py", line 86, in schema
    self._load_schema("service.yaml")
  File "/home/nonroot/task-core/task_core/schema.py", line 43, in _load_schema
    os.path.join(self.schema_folder, filename), encoding="utf-8", mode="r"
  File "/usr/lib64/python3.8/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by bogdando** [comment]
Nvm, switching it back to pypi install worked again: ``sudo /opt/directord/bin/pip3 install task-core/``
